import os
import smtplib
import imghdr
from email.message import EmailMessage

EMAIL_ADDRESS = os.environ.get('GMAIL_USER')
EMAIL_PWD = os.environ.get('GMAIL_PWD')

# use for when email multiple people

class followUpEmail:
    def __init__(self, email, subject):
        self.email = email
        self.subject = subject

    def sendEmail(self):
        msg = EmailMessage()
        msg['Subject'] = self.subject
        msg['From'] = EMAIL_ADDRESS
        msg['To'] = self.email
        msg['BCC'] = "agarrido84@gmail.com"
        msg.set_content("""\
        Hi! Enjoy the rest of the week, and I hope to hear from you soon.
        Abel Garrido
        Web Developer
        Mobile: 303-999-6683
        https://bohemianabe.github.io/proPage3
        """)
        msg.add_alternative("""\
        <!DOCTYPE html>
        <html lang="en">
  <body style="padding: 5px">
    <h2 style="color: SlateGray; padding-bottom: 5px">
      Hi! &#128075; I just wanted to follow up.
    </h2>
    <p style="color: rgb(32, 32, 32)">
      Hi Will these are just a few examples I was able to make this morning.
    </p>
    <p style="color: rgb(32, 32, 32)">
      After a little bit of altering my own email... (these are automatically
      generated by a python script program I wrote) I will definitely
      incorporate it in my own professional email.
    </p>
    <p style="color: rgb(32, 32, 32)">
      I can make any adjustments you need. I'm here to help you.
    </p>
    <div
      style="
        display: flex;
        flex-direction: row;
        padding: 2px;
        width: 100%;
        height: 100%;
        justify-content: space-between;
      "
    >
      <div class="photo" style="width: 75px; margin-right: 5px">
        <img
          style="height: 100%; width: 100%"
          src="./selfPortrait.jpg"
          alt=""
        />
      </div>
      <div
        class="details"
        style="
          line-height: 0%;
          width: auto;
          font-size: 12px;
          justify-content: end;
          display: flex;
          flex-direction: column;
        "
      >
        <p style="color: rgb(32, 32, 32); font-weight: bold">Abel Garrido</p>
        <p style="color: rgb(32, 32, 32)">Web Developer</p>
        <p style="color: rgb(32, 32, 32)">mobile: 303-999-6683</p>
        <p style="font-size: smaller">
          <a
            style="color: darkblue"
            href="https://bohemianabe.github.io/proPage3"
            >website/portfolio</a
          >
        </p>
      </div>
    </div>
    <p
      style="
        text-align: right;
        font-size: smaller;
        color: black;
        margin-top: 8px;
        font-style: italic;
      "
    >
      This email was brought to you by the power of Python. Work Smarter.
    </p>
  </body>
</html>
            """, subtype='html')


        with smtplib.SMTP_SSL('smtp.gmail.com', 465) as smtp:
            smtp.login(EMAIL_ADDRESS, EMAIL_PWD)
            smtp.send_message(msg)


test = followUpEmail("agarrido84@gmail.com", "email signature")

test.sendEmail()